<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Regression tests" duration-ms="13735" started-at="2022-10-16T13:37:31 EEST" finished-at="2022-10-16T13:37:45 EEST">
    <groups>
    </groups>
    <test name="Regression" duration-ms="13735" started-at="2022-10-16T13:37:31 EEST" finished-at="2022-10-16T13:37:45 EEST">
      <class name="tests.LoginTest">
        <test-method status="PASS" signature="setupSuite()[pri:0, instance:tests.LoginTest@6928f576]" name="setupSuite" is-config="true" duration-ms="9857" started-at="2022-10-16T13:37:31 EEST" finished-at="2022-10-16T13:37:41 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method status="PASS" signature="setupTest()[pri:0, instance:tests.LoginTest@6928f576]" name="setupTest" is-config="true" duration-ms="136" started-at="2022-10-16T13:37:41 EEST" finished-at="2022-10-16T13:37:41 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="beforeMethodActions()[pri:0, instance:tests.LoginTest@6928f576]" name="beforeMethodActions" is-config="true" duration-ms="834" started-at="2022-10-16T13:37:41 EEST" finished-at="2022-10-16T13:37:42 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodActions -->
        <test-method status="PASS" signature="verifyUserIsAbleToLogin()[pri:0, instance:tests.LoginTest@6928f576]" name="verifyUserIsAbleToLogin" duration-ms="2318" started-at="2022-10-16T13:37:42 EEST" finished-at="2022-10-16T13:37:44 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserIsAbleToLogin -->
        <test-method status="PASS" signature="afterMethodActions(java.lang.reflect.Method)[pri:0, instance:tests.LoginTest@6928f576]" name="afterMethodActions" is-config="true" duration-ms="145" started-at="2022-10-16T13:37:44 EEST" finished-at="2022-10-16T13:37:44 EEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTest.verifyUserIsAbleToLogin()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodActions -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:tests.LoginTest@6928f576]" name="closeDriver" is-config="true" duration-ms="227" started-at="2022-10-16T13:37:44 EEST" finished-at="2022-10-16T13:37:45 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.NegativeTest">
        <test-method status="PASS" signature="setupSuite()[pri:0, instance:tests.NegativeTest@3f093abe]" name="setupSuite" is-config="true" duration-ms="9861" started-at="2022-10-16T13:37:31 EEST" finished-at="2022-10-16T13:37:41 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method status="PASS" signature="setupTest()[pri:0, instance:tests.NegativeTest@3f093abe]" name="setupTest" is-config="true" duration-ms="997" started-at="2022-10-16T13:37:41 EEST" finished-at="2022-10-16T13:37:42 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="FAIL" signature="verifyThatErrorMessageIsShownIfEnterWrongLoginData()[pri:0, instance:tests.NegativeTest@3f093abe]" name="verifyThatErrorMessageIsShownIfEnterWrongLoginData" duration-ms="1228" started-at="2022-10-16T13:37:42 EEST" finished-at="2022-10-16T13:37:43 EEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error should be shown. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error should be shown. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at tests.NegativeTest.verifyThatErrorMessageIsShownIfEnterWrongLoginData(NegativeTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyThatErrorMessageIsShownIfEnterWrongLoginData -->
        <test-method status="PASS" signature="afterMethodActions(java.lang.reflect.Method)[pri:0, instance:tests.NegativeTest@3f093abe]" name="afterMethodActions" is-config="true" duration-ms="267" started-at="2022-10-16T13:37:44 EEST" finished-at="2022-10-16T13:37:44 EEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.NegativeTest.verifyThatErrorMessageIsShownIfEnterWrongLoginData() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodActions -->
      </class> <!-- tests.NegativeTest -->
    </test> <!-- Regression -->
  </suite> <!-- Regression tests -->
</testng-results>
